### ISSUE TITLE
Improve I/O for all steps

### ISSUE THREAD

**Issue by nicolaschotard** [nicolaschotard/Clusters#10]
Improve I/O system for all steps of the pipeline:

- Two files are produced by clusters_data.py:
  - cat.hdf5
  - cat_filtered.hdf5
- The next steps should not produce more files but increment the "filtered" one with new "paths"
- Each "path" can have a different format or size -> document that
- Input for a given script should always have the same format, e.g., 
  - script.py config.yaml input.hdf5 (--output if really needed)
  - option should be given in the config file, but could be overwritten in the command line
- Info should be added in the column description of the astropy tables (e.g., for the cuts in clusters_background.py)
- Config file should include keys for extinction run, zphot run, etc. E.g.:
  - 'zphot': {'lph': {'zparam': [...]}, 'bpz': {...}}
- zphot astropy table will contain the same amount of colmns for each 'zphot' runs (for lephare or pbz, or for different configuration of each)

**Comment by deapplegate** [comment]
To clarify: Each pipeline module should store all new output in the same (input) hdf5, right?
Would also suggest that each module should provide read methods such that (config.yaml, input.hdf5) -> astropy table(s) with fixed format and naming.

**Comment by nicolaschotard** [comment]
Yes, that was exactly our purpose, to have one single file along the whole chain. As for the fixed format and naming, we also discussed that with Céline to follow your suggestion at the hack week, and I simply forgot to add it in the list above. New bullet:

- each module should provide read methods such that (config.yaml, input.hdf5) -> astropy table(s) with fixed format and naming.

**Comment by combet** [comment]
Pushed a new branch called 'in_out', to start working on these I/O issues...

**Comment by combet** [comment]
New input/output implemented for all steps of the pipeline up to `clusters_getbackground`. Default usage now is `clusters_xxx config.yaml cat.hdf5`.

Nothing yet done regarding the `clusters_mass` step. Need to decide what information to store in the hdf5 file.
