### ISSUE TITLE
Break up main.py, moving codes into corresponding modules

### ISSUE THREAD

**Issue by deapplegate** [nicolaschotard/Clusters#14]
This avoids having each script dependent on the entire codebase via the import statements at the start of main.py.

**Comment by nicolaschotard** [comment]
Instead of moving the codes into the corresponding libraries (i.e., move load_data from main,py into data.py), I suggest that we move all part of the main.py into several independent python files stored in a main/ directory (load_data -> main/data.py). The structure of the code would thus be:

- clusters/

**Comment by deapplegate** [comment]
Isn't that the intent of the scripts directory? Ideally, no processing should happen in the scripts code, just forwarding arguments and options, so that'd be consistent.

**Comment by nicolaschotard** [comment]
Done in commit 10d7c8913805a6ca367f6864e6be7c6abfabd52f. New structure is as followed:

- clusters/
  - data.py
  - zphot.py
   - mains/
        - data.py
        - zphot.py

This changes are transparent to users. 

clusters/main.py is now deprecated and will be removed soon.

**Comment by nicolaschotard** [comment]
Things to do before closing this issue:

- remove the call to main.py in tests/test_clusters.py, and propagate that modification
- make sure main.py isn't called anywhere else
- make sure everything work fine, and remove main.py

**Comment by nicolaschotard** [comment]
Everything looks clean. main.py deleted in commit d2518377d2dbc960ab04a0b37360c8bd01d4860f. Close this issue.
