### ISSUE TITLE
Build fake-p(z) module to support image simulation tests

### ISSUE THREAD

**Issue by nicolaschotard** [nicolaschotard/Clusters#18]
Will allow to run simulated  data through the pipeline

**Comment by nicolaschotard** [comment]
Add a "sim" key word in config.yaml. 

`sim = {'flag': True/False, 'zfile': 'pathtotheredshiftfile'}`

If `flag` is True, `clusters_zphot.py` will use the `zfile` a file containing the redshift for all simulated galaxies (.txt file, id + zphot columns). It will then add what is needed to run `cluters_mass.py`.

**Comment by combet** [comment]
Done as described above. Robert and Ian contacted to get update on simulations, discuss file formats...

**Comment by nicolaschotard** [comment]
Should we close that issue?

**Comment by combet** [comment]
It's partially done in the sense that it assumes the user will provide a zfile with [id, redshift] where id is the DM stack id. So some matching is therefore required between the input and output galaxy catalogs and I'm not sure if this should be done in the pipeline (but we'd need access to the input catalog), or if we request it from the user... For the moment it wasn't an issue as all background galaxies were at the same redshift.

I'm going to close it for now and assume the user will provide such file. We can always revisit the question if we find it's more practical to do this matching within the pipeline...
