### ISSUE TITLE
clusters_data is broken because butler tables have changed

### ISSUE THREAD

**Issue by boutigny** [nicolaschotard/Clusters#19]
cluster_data is broken when running on most recent stack output because there is a new butler table and the fits extension number of the table that contains the (visit, ccd) information is now 8 instead of 7.

The choice has been to use the fitsio.read function instead of the butler for performance reasons. I think that this should be re-assessed as we will never get the insurance that the structure of the fits tables do not change.

**Comment by nicolaschotard** [comment]
Should be fixed in commit e1d3ff3a7980568416c9a24e5accc1746be72d66

**Comment by boutigny** [comment]
Yes it works
